export const VIDEOS_REQUEST = 'VIDEOS_REQUEST';
export const VIDEOS_SUCCESS = 'VIDEOS_SUCCESS';
export const VIDEOS_FAILURE = 'VIDEOS_FAILURE';
export const VIDEOS_ERROR_CLEANUP = 'VIDEOS_ERROR_CLEANUP';
export const VIDEOS_RESET = 'VIDEOS_RESET';
